name: Trigger netlify build

on:
  schedule:
    # Run at 00:00 daily
    - cron: '0 0 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Curl request
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
