name: Trigger netlify build

on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  build:
    name: Build request netlify
    runs-on: ubuntu-latest

    steps:
      - name: Curl request
        run: curl -X POST -d '{}' NETLIFY_BUILD_HOOK
        with:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
